### ISSUE TITLE
野菜を拾ったら手で持つようにする

### ISSUE THREAD

**Issue by AoichiShisho** [AoichiShisho/YassaiMossai#31]
fix

**Comment by tsunufu** [comment]
ref #42

**Comment by tsunufu** [comment]
一つのアイテムしか持つことができない．アイテムを持っていても種を植えることはできる

**Comment by tsunufu** [comment]
![Image](https://github.com/AoichiShisho/YassaiMossai/assets/73733296/6bca2af2-5c55-46da-8bc4-2dc1b7309643)

- 赤枠のところいらない
- バスケットとかクワを切り替える部分は自分が何を持ってるかを表示させることに変更する
- バスケットとジョウロは意志
- クワはPlayerに持たせる
